apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow-server
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001"]
