apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30000  # This is the port you will use to access MLflow
